export const OPEN_MODAL_VIDEO = 'OPEN_MODAL_VIDEO';
export const CLOSE_MODAL_VIDEO = 'CLOSE_MODAL_VIDEO';

export const ADD_COMMENT_MODAL = 'ADD_COMMENT_MODAL';
export const ADD_LIKE_COMMENT_MODAL = 'ADD_LIKE_COMMENT_MODAL';