export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM';

export const LAY_THONG_TIN_HE_THONG_RAP = 'LAY_THONG_TIN_HE_THONG_RAP';
export const LAY_DS_CUM_RAP_THEO_HE_THONG = 'LAY_DS_CUM_RAP_THEO_HE_THONG';
export const SET_TEN_HE_THONG_RAP = 'SET_TEN_HE_THONG_RAP';
export const LAY_THONG_TIN_LICH_CHIEU_THEO_RAP = 'LAY_THONG_TIN_LICH_CHIEU_THEO_RAP';
export const LAY_MA_CUM_RAP = 'LAY_MA_CUM_RAP'

export const LAY_THONG_TIN_LICH_CHIEU_CHI_TIET_PHIM = 'LAY_THONG_TIN_LICH_CHIEU_CHI_TIET_PHIM'

export const LAY_THONG_TIN_PHONG_VE = 'LAY_THONG_TIN_LICH_CHIEU_CHI_TIET_PHIM';

export const CHON_GHE = 'CHON_GHE';

export const DAT_vE = 'DAT_VE'