export const LAY_USER_DANG_NHAP = 'LAY_USER_DANG_NHAP'

export const DANG_XUAT = 'DANG_XUAT'

export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG'

export const LAY_THONG_TIN_CA_NHAN = 'LAY_THONG_TIN_CA_NHAN'

export const LAY_THONG_TIN_CAP_NHAT = 'LAY_THONG_TIN_CAP_NHAT'

export const CHANGE_THONG_TIN_CAP_NHAT = 'THAY_DOI_THONG_TIN_CAP_NHAT'